### ISSUE TITLE
Let's ditch ordinals!

### ISSUE THREAD

**Issue by volodeyka** [volodeyka/event-struct#20]
We had such definition of `exec_event_structures`
```Coq
Structure exec_event_struct := Pack {
  N     : nat;
  lab   : 'I_N -> label;
  fpred : forall m : 'I_N, 'I_m.+1;
  frf   : forall (r : 'I_N), {w : 'I_r.+1 |
                              (w == r :> nat) (+) write_read_ext lab w r}
}.
```
 And we decided to stop using dependent types and ordinals. And abstract to a random subset of `identType` (instead of ordinals). So we want to have `E : identType` and `lab`, `fpred`, `frf` to be functions defined on its finite subset. That's why we need a structure for a subclass of finite functions.

My idea was to make a structure which would be parametrized by  
1) `Dome Codome : eqType` -- domain and codomain Type
2) `dom : n.-tuple Dome` or `dom : {fset Dome}`... -- elements on with our finite function will be defined
3) `r : Dome -> Codome -> bool` -- relation s.t. our function must be a sub relation of `r`
4) `dflt : Dome -> Codome` -- default function to coerce our finite function on the whole `Dome`
And our structure of finite function should contain: 
1) somehow coded finite function `f` on elements of `dom`
2) proof that `forall x, r x (f x)` (for example for `fpred` we should take `r := <=`)

Now I'm thinking to do something like that:
```Coq
Structure rffun {n : nat} {Dome : choiceType} {Codome : eqType}
  (dflt : Dome -> Codome) (dom : {fset Dome}) (r : Dome -> Codome -> bool) := 
  Rffun {
  f : {ffun dom -> Codome};
  #[canonical(false)] dep : [forall x : dom, r (fsval x) (f x)]
}.
```
Any suggestions?

**Comment by volodeyka** [comment]
Should we close it for now?

**Comment by anton-trunov** [comment]
Yeah, looks like we've moved on.
