### ISSUE TITLE
Map needs more information

### ISSUE THREAD

**Issue by volodeyka** [volodeyka/event-struct#33]
Now we have one problem: while applying `map` to some sequence, we sometimes need the information that elements of the sequence (say `s`) to which we are trying to apply our `map` are really in `s`. In other words, if we have `f : forall x, x \in s -> T` we can't just apply it to `s` via `map`. Also we can't just check on each step "if the element `x` is actually in `s`", because it leads to  `O(n^2)` complexity after extraction.
We faced this problem in `relation.v` : https://github.com/volodeyka/event-struct/blob/0c1de9689b54391059204b89b40077735b19182c/relations.v#L45
and in `regmachine.v`: https://github.com/volodeyka/event-struct/blob/9e64017e0ce3d03fd7f88e0d270d259b26f905ac/regmachine.v#L128
Where it was decided to check if `x \in s` on each step as a temporary solution.
So think we can try to deal with this problem here. I have got a hand-made solution:
```Coq
Definition  mem_map {T} {S : eqType} (s : seq S)
  (f : forall x, x \in s -> T) : seq T :=
  let fix mem_map_aux (s' : seq S):= 
    match s' with
    | h :: t => fun (sub : subseq (h :: t) s) => 
      f _ (mem_subseq sub (mem_head h t)) ::
      mem_map_aux t (subseq_trans (subseq_cons t h) sub)
    | [::] => fun=> [::]
    end in
  mem_map_aux s (subseq_refl s).
```
But I suppose it possible to reuse something from `mathcomp` and not reinvent the wheel or just come up with a nicer solution.

**Comment by volodeyka** [comment]
PS. if we decide yo do something like `mem_map`, we can prove the lemma like:
```Coq
Lemma mem_map_map T (S : eqType) (s : seq S)
(f : forall x, x \in s -> T) d : 
  mem_map s f = 
  map (fun x =>
    if x \in s =P true is ReflectT pf then
      f _ pf
    else d) s.
```

**Comment by eupp** [comment]
The name `mem_map` clashes with the lemma from `ssreflect/seq.v`

**Comment by volodeyka** [comment]
> The name `mem_map` clashes with the lemma from `ssreflect/seq.v`

`map_mem` then? Or `map_in`...

**Comment by anton-trunov** [comment]
I'll comment on this issue a bit later, but one minor observation is that it looks a lot like OCaml's `List.mapi` function which takes an element and its index within the input list (the index corresponds to the membership proof).

**Comment by eupp** [comment]
> > The name `mem_map` clashes with the lemma from `ssreflect/seq.v`
> 
> `map_mem` then? Or `map_in`...

I like `map_in`, but check for the name clash in vanilla stdlib and ssreflect.


> I'll comment on this issue a bit later but one minor observation is that it looks a lot like OCaml's `List.mapi` function which takes an element and its index within the input list (the index corresponds to the membership proof).

You mean that it is semantically similar, or that we can get the desired behavior using `mapi`?

**Comment by volodeyka** [comment]
So, as @anton-trunov said, using the function with dependent types in big proofs can cause many problems, we should think of another way to deal with this problem. I have some proposals on what we can do in `relations.v` and `regmachine.v`:

- `relations.v`
  1. We safely can redo `relations.v` on `map_in` because now we use definitely the same thing there as in `map_inE` lemma: https://github.com/volodeyka/event-struct/blob/90f874c05c9dd5f17d7794d7102cc5890ec790fb/relations.v#L44-L48
  `map_in` will only be here a quick implementation of the code we have now. When we want to prove something, we will simply use `map_inE` and write the same proof we have now.
  2. As far as the problem is in the casing on `x \in ys` when we just need `x < n`, let's case on `x < n`:
      ```Coq
      if x < n =P true is ReflectT pf then 
           s_up_set x
      else
      ```
      if we can decide `x < n` or not quickly (in natural numbers, for example, we can), this calculation will not lead to `O(n^2)` on   each step of recursion
      **But** comparing strings or something like that is not so fast and can cause a low speed
  3. We can use `Fix`. There we have recursion on `acc`-predicate and perhaps it is quite effective(?)
- `regmachine.v`
   The main problem here is that when we want to add something to our event structure, we need to build the `add_label` record which contains:
  https://github.com/volodeyka/event-struct/blob/90f874c05c9dd5f17d7794d7102cc5890ec790fb/transitionsystem.v#L73-L78
  Then in `regmachine.v` we must in the given event structure find special `Write`-events and put them in `add_label`.  To statisfy `add_write_in_dom` in `es_seq`
  https://github.com/volodeyka/event-struct/blob/90f874c05c9dd5f17d7794d7102cc5890ec790fb/regmachine.v#L175-L187
  we have to write something like that:
  https://github.com/volodeyka/event-struct/blob/90f874c05c9dd5f17d7794d7102cc5890ec790fb/regmachine.v#L155-L156
  Where we decide whether for each element `y` from `dom` holds `y \in dom` -- it is a redundant check that leads to the `O(n^2)` speed. 
  1. We can store `ffpred` and `ffrf` not as functions from the `dom` elements to their predecessors (which are in `dom` too), but as  functions from the `dom` elements to indexes of their `dom`'s predecessors. Because it is easy either check if given natural number `n` is the index of an element in `dom` or to transform it to the index of an element in `dom`.
    In this case, it is quite easy to write `write_seq` function that by given event structure returns all indexes of it's events satisfying some property in `O(n)`
  2. Another way to implement `write_seq` is first to filter `dom` by `wpred x` and then to transform it into `fset` and implement `es_seq` not as a mapping from the sequence of all events adaptable to the corresponding event structures, but as a set-to-set mapping where we can obtain all needed information from elements type.
    **BUT** as the output we have **set** of `exec_event_structures`, so we need to prove that it is a `choiceType` (it seems like a "try hard")
   **one more but** I don't know if the transformation from `seq` to `fset` takes not more then `O(n)`
